### ISSUE TITLE
Python 3.6 import mlflow not working.

### ISSUE THREAD

**Issue by thoward27** [databricks/mlflow#151]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **MLflow installed from (source or binary)**:  Binary
- **MLflow version (run ``mlflow --version``)**: 0.2.1
- **Python version**: 3.6
- **npm version (if running the dev UI): 
- **Exact command to reproduce**: import mlflow

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in MLflow or a feature request.

Receiving the following traceback when trying to import mlflow into my project. I am using a python 3.6 virtualenv within Pycharm. Steps to reproduce: 

1. `pip install mlflow`
2. from within a module: `import mlflow`

protobuf version number 3.6

Results are the same if mlflow is installed from within the Pycharm interpreter manager. 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/tom/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.5087.37/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tom/Documents/uri/reinforcement-learning-compilers/.venv/lib/python3.6/site-packages/mlflow/__init__.py", line 4, in <module>
    import mlflow.projects as projects  # noqa
  File "/home/tom/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.5087.37/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tom/Documents/uri/reinforcement-learning-compilers/.venv/lib/python3.6/site-packages/mlflow/projects.py", line 17, in <module>
    from mlflow.entities.param import Param
  File "/home/tom/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.5087.37/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tom/Documents/uri/reinforcement-learning-compilers/.venv/lib/python3.6/site-packages/mlflow/entities/param.py", line 2, in <module>
    from mlflow.protos.service_pb2 import Param as ProtoParam
  File "/home/tom/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.5087.37/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tom/Documents/uri/reinforcement-learning-compilers/.venv/lib/python3.6/site-packages/mlflow/protos/service_pb2.py", line 18, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "/home/tom/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.5087.37/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tom/Documents/uri/reinforcement-learning-compilers/.venv/lib/python3.6/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 25, in <module>
    dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

**Comment by thoward27** [comment]
To those who may face this same issue,
I've been able to resolve the error by switching the order of installs to my virtualenv, if I install mlflow before tensorflow, this issue doesn't occur.

As far as this issue goes, I'm going to close it here, since it doesn't necessarily appear to be an MLFlow issue.
