### ISSUE TITLE
[Permission denied] when using a tracking server

### ISSUE THREAD

**Issue by bbbxxxbx** [databricks/mlflow#212]
**Describe the problem**

1. Use a remote server as the tracking server and configuration for the server is as follow:
```
mlflow server --file-store /root/mlflow/mlruns  --host 0.0.0.0
```

2. Change the `train.py` file in example as follow:
![image](https://user-images.githubusercontent.com/14008396/43380307-46ea2c58-9403-11e8-9a39-42aa88b64c2e.png)

3. Run the `train.py` file in local and has an error.The log is as follow:
```
Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.82224284975954
  MAE: 0.6278761410160691
  R2: 0.12678721972772689
Traceback (most recent call last):
  File "trainTest.py", line 67, in <module>
    mlflow.sklearn.log_model(lr, "model")
  File "/home/baoxu/anaconda2/lib/python2.7/site-packages/mlflow/sklearn.py", line 54, in log_model
    mlflow.tracking.log_artifacts(local_path, artifact_path)
  File "/home/baoxu/anaconda2/lib/python2.7/site-packages/mlflow/tracking/__init__.py", line 323, in log_artifacts
    _get_or_start_run().log_artifacts(local_dir, artifact_path)
  File "/home/baoxu/anaconda2/lib/python2.7/site-packages/mlflow/tracking/__init__.py", line 134, in log_artifacts
    self.artifact_repo.log_artifacts(local_dir, artifact_path)
  File "/home/baoxu/anaconda2/lib/python2.7/site-packages/mlflow/store/artifact_repo.py", line 99, in log_artifacts
    mkdir(artifact_dir)
  File "/home/baoxu/anaconda2/lib/python2.7/site-packages/mlflow/utils/file_utils.py", line 99, in mkdir
    raise e
OSError: [Errno 13] Permission denied: '/root/mlflow/mlruns/0/7ca3c61e98b848d9bc57308979b362cb/artifacts/model'
```
4. Check the tracking server and find that `metrics` and  `params` are OK, but `model` has nothing.
![image](https://user-images.githubusercontent.com/14008396/43380167-a951ab88-9402-11e8-8b64-c2452a0f96d0.png)

**System information**

1. OS Platform of both:14.04.1-Ubuntu
2. python version: 2.7.15
3. mlflow version:0.3.0

**Comment by arnabbiswas1** [comment]
@aarondav This is in continuation with the discussion we were having (at mlflow-users group : [Link](https://groups.google.com/forum/#!topic/mlflow-users/vyq2eJqDU0k)) related to default-artifact-root. You may want to reopen this issue to address the documentation.

[Aaron]  We should probably explicitly document NFS in the Storage section here: https://github.com/mlflow/mlflow/blob/master/docs/source/tracking.rst

**Comment by Towhid1** [comment]
facing same issue.
