### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by adberard** [databricks/mlflow#3]
Hello ! 
So I just decided to try mlflow ! However after installing conda with the installer.sh and pip install mlflow it seems that it really work as intended.
I am on Arch Manjaro. 
```
~ ❯ mlflow
Traceback (most recent call last):
  File "/usr/bin/mlflow", line 7, in <module>
    from mlflow.cli import cli
  File "/usr/lib/python3.6/site-packages/mlflow/__init__.py", line 8, in <module>
    import mlflow.projects as projects # noqa
  File "/usr/lib/python3.6/site-packages/mlflow/projects.py", line 18, in <module>
    from mlflow.entities.param import Param
  File "/usr/lib/python3.6/site-packages/mlflow/entities/param.py", line 2, in <module>
    from mlflow.protos.service_pb2 import Param as ProtoParam
  File "/usr/lib/python3.6/site-packages/mlflow/protos/service_pb2.py", line 127, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

```

How do I solve this ?

**Comment by adberard** [comment]
Now working after reinstalling
