### ISSUE TITLE
Python 3.5 example/tutorial Json encoding error

### ISSUE THREAD

**Issue by manugarri** [databricks/mlflow#8]
When running `mlflow run example/tutorial -P alpha=0.4` with python=3.5.3 there is a json encoding issue:

```
manuel@manuel mlflow (master) $ mlflow run example/tutorial -P alpha=0.4
=== Fetching project from example/tutorial ===
=== Work directory for this run: example/tutorial ===
=== Created directory /tmp/tmp8xm4tafv for downloading remote URIs passed to arguments of type 'path' ===
Traceback (most recent call last):
  File "/home/manuel/anaconda3/envs/test/bin/mlflow", line 11, in <module>
    sys.exit(cli())
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/mlflow/cli.py", line 117, in run
    use_temp_cwd=new_dir, storage_dir=_encode(storage_dir))
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/mlflow/projects.py", line 284, in run
    storage_dir=storage_dir)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/mlflow/projects.py", line 247, in _run_local
    _run_project(project, entry_point, work_dir, parameters, use_conda, storage_dir, experiment_id)
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/site-packages/mlflow/projects.py", line 374, in _run_project
    env_names = [os.path.basename(env) for env in json.loads(stdout)['envs']]
  File "/home/manuel/anaconda3/envs/test/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by manugarri** [comment]
I see the issue is [here](https://github.com/databricks/mlflow/blob/master/mlflow/projects.py#L373) that calls [this function in utils](https://github.com/databricks/mlflow/blob/master/mlflow/utils/process.py#L37) that uses subprocess.Popen, that returns bytes instead of a str (which is what json.loads expects). 

Are you guys making mlflow p2 compatible? if not this should be a quick fix.

**Comment by smurching** [comment]
Thanks for reporting this @manugarri :). For now we would like to make MLflow Python 2 compatible, I think we can do it by passing `universal_newlines=True` to `subprocess.Popen`. Would you be interested in opening a PR?

**Comment by manugarri** [comment]
fixed in https://github.com/databricks/mlflow/pull/15
